server:
  port: 8081

facebook:
  client:
    clientId: 1031537590356503
    clientSecret: aa72e1ac7d57a4ad72249c1e56f47913
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
google:
  client:
    clientId: 714228005236-t1kul05936v3gi1jlvgne9qn11djnh17.apps.googleusercontent.com
    clientSecret: dvekbf4PXnOdCZOQ4XIYQF-i
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo
spring:
  data:
    mongodb:
      database: mobilelog
      username: mobilelog
      password: 3482mobilelog2004
      port: 27017
      host: 121.78.124.180
      uri: mongodb://121.78.124.180:27017/mobilelog
#  mvc:
#    static-path-pattern: /static/**